### ISSUE TITLE
The executable doesn't launch the program

### ISSUE THREAD

**Issue by stardvst** [nicolasraube/greedy-pathfinding#1]
The following is printed in terminal when I compile and execute the program:

`Error: A JNI error has occurred, please check your installation and try again.
Exception in thread "main" java.lang.UnsupportedClassVersionError: Main has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
`

Java version:
`$ openjdk version "1.8.0_102"`
`$ OpenJDK Runtime Environment (build 1.8.0_102-b14)`
`$ OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)`

**Comment by nicolasraube** [comment]
Hi, thank you for your contribution. First thing I'm thinking of: are you able to update your JRE?

**Comment by stardvst** [comment]
Updated to the latest build (Java SE Runtime Environment 8u172) but still getting the same error.

**Comment by nicolasraube** [comment]
How are you executing the .jar file?

**Comment by nicolasraube** [comment]
I get the error if I try to launch the .jar from the terminal as well. Can you try executing by double-clicking?

**Comment by stardvst** [comment]
I get an error message box, saying:
"Error: A JNI error has occurred, please check your installation and try again"

**Comment by nicolasraube** [comment]
I uploaded a new version of the .jar file. Please download and try again.

**Comment by mlilia** [comment]
This one works. Thanks!

**Comment by nicolasraube** [comment]
Thank you for your participation!
For anyone wondering: in IntelliJ IDEA I have lowered the "project language level" in the project settings from 9 to 8 and rebuilt the .jar file.
